# Generated by Django 3.1.7 on 2021-07-17 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0)),
            preserve_default=False,
        ),
    ]
