# Generated by Django 4.0.1 on 2022-01-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0004_accountinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinformation',
            name='email_to',
            field=models.EmailField(default='n', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='google_account_email',
            field=models.EmailField(default='jmoutinho94@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='google_account_password',
            field=models.TextField(default='n'),
            preserve_default=False,
        ),
    ]
