# Generated by Django 4.0.1 on 2022-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0005_accountinformation_email_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsteopathyAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='osteopathyabout',
            name='text_advantages',
        ),
        migrations.AddField(
            model_name='osteopathyabout',
            name='image_where',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osteopathyabout',
            name='image_who',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
