# Generated by Django 4.0.1 on 2022-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0006_osteopathyadvantages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='osteopathyhistory',
            name='image',
            field=models.ImageField(default='', upload_to='eso/static/eso/media/image_history'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osteopathyhistory',
            name='quote_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osteopathyabout',
            name='image_where',
            field=models.ImageField(upload_to='eso/static/eso/media/image_about_where'),
        ),
        migrations.AlterField(
            model_name='osteopathyabout',
            name='image_who',
            field=models.ImageField(upload_to='eso/static/eso/media/image_about_who'),
        ),
    ]
