# Generated by Django 4.0.1 on 2022-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0007_delete_appointment_osteopathyhistory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PediatricOstepathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PediatricOstepathyReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
    ]
