# Generated by Django 4.0.1 on 2022-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0009_rename_text_pediatricostepathy_top_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPresentationParagrapth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextPresentationSpecialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='textpresentation',
            old_name='text',
            new_name='credentials',
        ),
    ]
