# Generated by Django 4.0.1 on 2022-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eso', '0010_textpresentationparagrapth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentGeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_appointment_min_time', models.TextField()),
                ('first_appointment_max_time', models.TextField()),
                ('first_appointment_base_price', models.TextField()),
                ('second_appointment_min_time', models.TextField()),
                ('second_appointment_max_time', models.TextField()),
                ('second_appointment_base_price', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentsImportantNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
